# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15766b4b043af3c6b41b7572c1fca5f12ecc77ceb95d0fdca7eb914b8632447a1152f7bc260095322911d7e3bfd73613b9c6fe8002138b4e8ee18394258b61f5

test:
  secret_key_base: 897233887684b5bf4004df9ba9dbaa929cb005afbe78d829e2b8113be69b73442826bc8c9b3e0c2cf944454951b9651e4331157f52d6a3cab16b464ac7f4ade1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
